### PR TITLE
Update "master" to "main"

### PR DESCRIPTION
**Pull request by william-monroy**
I replace every terminology "master" with "main" in the repository. Issue #10 

- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
There is a mix of terms here. "main" is recommended for primary Branch names, but the Jenkins entity is officially a "controller" not nain. It needs update

**Comment by william-monroy** [comment]
Hi @oleg-nenashev  , I am a bit new to the subject and I would be very grateful if you could share with me some resources to learn more or maybe explain to me a bit more specifically what files I should modify.

**Comment by lemeurherve** [comment]
@william-monroy you'll find here some explainations for these terms: https://www.jenkins.io/doc/book/glossary/#master

**Comment by oleg-nenashev** [comment]
This is probably a better link for contributors:
https://community.jenkins.io/t/jenkins-terminology-cleanup-initiative-coordination/180

**Comment by oleg-nenashev** [comment]
Closing in favor of #21

**Pull request closed without merging**
